name:  Continuous Integration

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main

jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      App_Packages_Directory: AppPackages
      SigningCertificate: GitHubActions.pfx
      Solution_Path: GolemUI.sln
      #Test_Project_Path: MyWpfApp.Tests\MyWpfApp.Tests.csproj
      Wpf_Project_Path: GolemUI.csproj
      Wap_Project_Directory: AppPackage
      Wap_Project_Name: AppPackage.wapproj
      #Actions_Allow_Unsecure_Commands: true # Allows AddPAth and SetEnv commands

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.302'

      - name: Install formater
        run: dotnet tool install -g dotnet-format

      - name: Check formating
        run: dotnet-format --check GolemUI.sln

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name:  Restore obj folder
        run: msbuild $env:Solution_Path /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
        env:
          Configuration: Release
          RuntimeIdentifier: win-${{ matrix.targetplatform }}

      - name: Build the Windows Application
        run: msbuild $env:Solution_Path /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode
        env:
          AppxBundle: Never
          BuildMode: SideloadOnly
          Configuration: Release
          TargetPlatform: ${{ matrix.targetplatform }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: GolemUI
          path: bin\Release\netcoreapp3.1\
